site_name: Allsky Documentation
site_url: "https://docs.allsky.local"
site_dir: "html/docs"

repo_url: https://github.com/AllskyTeam/allsky
repo_name: Allsky

use_directory_urls: false

theme:
  name: material
  logo: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github
    tag:
      default: material/tag
      hw: material/chip
      sw: material/code-tags
      overlay: material/layers
      module: material/puzzle
      sensor: material/radar
      mqtt: material/access-point
      weather: material/weather-partly-cloudy
      power: material/power-plug
      network: material/lan
      experimental: material/flask 
      data: material/data-matrix
      extra: material/code-braces-box
      day: material/weather-sunny
      night: material/weather-night
      clock: material/clock-outline
      hardware: material/hammer
      api: material/api
      image: material/image
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - content.code.annotate
    - header.autohide
    - navigation.footer
    - search.suggest

extra:
  tags:
    Hardware: hw
    Software: sw
    Overlays: overlay
    Modules: module
    Sensors: sensor
    MQTT: mqtt
    Weather: weather
    Power: power
    Networking: network
    Experimental: experimental
    Data Capture: data
    Extra Module: extra
    Overlay Data: overlay
    Pipeline Day: day
    Pipeline Night: night
    Pipeline Periodic: clock
    Hardware Required: hardware
    API Required: api
    Image Adjustments: image

extra_css:
  - assets/css/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - offline
  - tags:
      tags_file: tags.md
  - glightbox:
      skip_classes:
        - skip-lightbox  
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
            - server
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            merge_init_into_class: true
            filters: public

markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde  
  - footnotes
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.arithmatex
  - pymdownx.blocks.caption
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true  
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Allsky Guide:
    - Installation: 
      - allsky_guide/allsky.md
      - allsky_guide/website.md
      - allsky_guide/server.md
    - Configuration: allsky_guide/configuration.md
    - Settings:
      - allsky_guide/settings/allsky.md
      - allsky_guide/settings/website.md
    - Howtos:
      - Allsky layout: allsky_guide/howtos/layout.md
      - Helper Tools: 
        - Startrails: allsky_guide/howtos/helper_tools/startrails.md
        - Image Stretch:  allsky_guide/howtos/helper_tools/image_stretch.md
    - Troubleshootings:
      - Reporting Problems: allsky_guide/troubleshooting/reporting.md
      - Tools: allsky_guide/troubleshooting/tools.md
      - Uploads (ftp, scp etc) :  allsky_guide/troubleshooting/uploads.md
      - Startrails: allsky_guide/troubleshooting/startrails.md
      - Timelapse: allsky_guide/troubleshooting/timelapse.md
      - Image Flicker: allsky_guide/troubleshooting/flicker.md
      - WebUI: allsky_guide/troubleshooting/webui.md
      - Website: allsky_guide/troubleshooting/website.md
      - Increase Swap Space: allsky_guide/troubleshooting/swap.md
      - ZWO Cameras: allsky_guide/troubleshooting/zwo.md
      - RPi Cameras: allsky_guide/troubleshooting/rpicam.md
      - Other Hardware: allsky_guide/troubleshooting/hardware.md
      - Others: allsky_guide/troubleshooting/others.md
    - FAQ: allsky_guide/faq.md
    - Hardware:
      - Pi Options: allsky_guide/hardware/pi.md
      - Camera Options: allsky_guide/hardware/camera.md
      - Lens Options: allsky_guide/hardware/lens.md
    - Known Issues: allsky_guide/known_issues.md
    - ChangeLog: allsky_guide/changelog.md
    - Things we love: allsky_guide/things.md 
    - 3d Printables: allsky_guide/3d.md   
    - Alternatives: allsky_guide/alternatives.md
    - Tags: tags.md    
  - Overlays:
    - Overview: allsky_guide/overlays/overview.md
    - How They Work: allsky_guide/overlays/how.md
    - Fields And Variables: allsky_guide/overlays/fieldsandvariables.md
    - Extra Data: allsky_guide/overlays/extra.md
    - Interface: allsky_guide/overlays/interface.md
    - Formatting Variables: allsky_guide/overlays/formatting.md
    - Tips: allsky_guide/overlays/tips.md
    - Sun and Moon: allsky_guide/overlays/sunmoon.md    
  - Modules:
    - Introduction: allsky_modules/introduction.md
    - Core Modules: 
      - Modules:
        - Load Image: allsky_modules/core/load_image.md
        - Save Image: allsky_modules/core/save_image.md
        - Mask Image: allsky_modules/core/mask_image.md
        - Overlay: allsky_modules/core/overlay.md
        - Exposure Rect: allsky_modules/core/exposure_rect.md
        - Histogram: allsky_modules/core/histogram.md
        - Star Count: allsky_modules/core/star_count.md
        - Meteor Count: allsky_modules/core/meteor_count.md
        - Clear Sky: allsky_modules/core/clear_sky.md
        - Export: allsky_modules/core/export.md
        - Pi Status: allsky_modules/core/pi_status.md
        - Imtermediate Image: allsky_modules/core/imtermediate_image.md
    - Extra Modules:
      - Environment: allsky_modules/extra/environment.md    
      - Dew Heater: allsky_modules/extra/dew_heater.md
      - ADSB: allsky_modules/extra/adsb.md
      - Border: allsky_modules/extra/border.md
      - Discord: allsky_modules/extra/discord.md
      - Round Displays: allsky_modules/extra/esp32round.md
      - Fans: allsky_modules/extra/fans.md
      - GPIO: allsky_modules/extra/gpio.md
      - Hard Disk Temp: allsky_modules/extra/hddtemp.md
      - Image Tuning: allsky_modules/extra/image_tuning.md
      - Power:  allsky_modules/extra/power.md
      - Publish Data: allsky_modules/extra/publish_data.md
      - JSON Import: allsky_modules/extra/json_import.md
      - Light Meter: allsky_modules/extra/light.md
      - Lightning: allsky_modules/extra/lightning.md
      - MLX90640: allsky_modules/extra/mlx90640.md
      - Open Weather Map: allsky_modules/extra/owm.md
      - GPS: allsky_modules/extra/gps.md
      - Air Quality: allsky_modules/extra/air_quality.md
      - Detect Rain: allsky_modules/extra/rain.md
      - Run Script: allsky_modules/extra/run_script.md
      - Solar System: allsky_modules/extra/solar_system.md
      - Sky Quality: allsky_modules/extra/sky_quality.md
      - Deprecated Modules:
        - INA3221: allsky_modules/extra/ina3221.md
        - MQTT Subscribe: allsky_modules/extra/mqtt_subscribe.md    
        - InfluxDB: allsky_modules/extra/influxdb.md
        - LTR390: allsky_modules/extra/ltr390.md          
  - Developer Guide:
    - Introduction: developer_guide/introduction.md
    - Glossary: developer_guide/glossary.md
    - Overview: developer_guide/overview.md
    - Modules:
      - Folder Strucuture: developer_guide/folder_structure.md
      - Module Structure: developer_guide/module_structure.md
      - Meta Data Structure: developer_guide/meta_data_structure.md
      - Meta Data Example: developer_guide/meta_data_example.md
      - Available Fields: developer_guide/available_fields.md
      - Shared Libraries: developer_guide/shared_libraries.md
      - Charts: developer_guide/charts.md
      - Blocks: developer_guide/blocks.md
      - Dependencies: developer_guide/dependencies.md
    - SDK Reference:
      - Shared Module: allsky_shared.md
      - Base Class: allsky_base.md
      - Allsky Server API: allsky_api.md
    - Contributing: developer_guide/contributing.md

