site_name: Allsky Documentation
site_url: "https://docs.allsky.local"
site_dir: "html/docs"

repo_url: https://github.com/AllskyTeam/allsky
repo_name: Allsky

use_directory_urls: false

theme:
  name: material
  logo: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - content.code.annotate
    - header.autohide
    - navigation.footer
    - search.suggest


extra_css:
  - assets/css/extra.css

plugins:
  - search
  - offline
  - glightbox:
      skip_classes:
        - skip-lightbox  
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
            - server
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            merge_init_into_class: true
            filters: public

markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde  
  - footnotes
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.arithmatex
  - pymdownx.blocks.caption
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Allsky Guide:
    - Installation: 
      - allsky_guide/allsky.md
      - allsky_guide/website.md
      - allsky_guide/server.md
    - Configuration: allsky_guide/configuration.md
    - Settings:
      - allsky_guide/settings/allsky.md
      - allsky_guide/settings/website.md
    - 3d Printables: allsky_guide/3d.md   
    - Alternatives: allsky_guide/alternatives.md
  - Overlays:
    - Overview: allsky_guide/overlays/overview.md
    - How They Work: allsky_guide/overlays/how.md
    - Fields And Variables: allsky_guide/overlays/fieldsandvariables.md
    - Extra Data: allsky_guide/overlays/extra.md
    - Interface: allsky_guide/overlays/interface.md
    - Formatting Variables: allsky_guide/overlays/formatting.md
    - Tips: allsky_guide/overlays/tips.md
    - Sun and Moon: allsky_guide/overlays/sunmoon.md    
  - Modules:
    - Introduction: allsky_modules/introduction.md
    - Core Modules: 
      - Modules:
        - Load Image: allsky_modules/core/load_image.md
        - Save Image: allsky_modules/core/save_image.md
        - Mask Image: allsky_modules/core/mask_image.md
        - Overlay: allsky_modules/core/overlay.md
        - Exposure Rect: allsky_modules/core/exposure_rect.md
        - Histogram: allsky_modules/core/histogram.md
        - Star Count: allsky_modules/core/star_count.md
        - Meteor Count: allsky_modules/core/meteor_count.md
        - Clear Sky: allsky_modules/core/clear_sky.md
        - Export: allsky_modules/core/export.md
        - Pi Status: allsky_modules/core/pi_status.md
        - Imtermediate Image: allsky_modules/core/imtermediate_image.md
    - Extra Modules:
      - Environment: allsky_modules/extra/environment.md    
      - Dew Heater: allsky_modules/extra/dew_heater.md
      - ADSB: allsky_modules/extra/adsb.md
      - Border: allsky_modules/extra/border.md
      - Discord: allsky_modules/extra/discord.md
      - Round Displays: allsky_modules/extra/esp32round.md
      - Fans: allsky_modules/extra/fans.md
      - GPIO: allsky_modules/extra/gpio.md
      - Hard Disk Temp: allsky_modules/extra/hddtemp.md
      - Image Tuning: allsky_modules/extra/image_tuning.md
  - Developer Guide:
    - Introduction: developer_guide/introduction.md
    - Glossary: developer_guide/glossary.md
    - Overview: developer_guide/overview.md
    - Modules:
      - Folder Strucuture: developer_guide/folder_structure.md
      - Module Structure: developer_guide/module_structure.md
      - Meta Data Structure: developer_guide/meta_data_structure.md
      - Meta Data Example: developer_guide/meta_data_example.md
      - Available Fields: developer_guide/available_fields.md
      - Shared Libraries: developer_guide/shared_libraries.md
      - Charts: developer_guide/charts.md
      - Blocks: developer_guide/blocks.md
      - Dependencies: developer_guide/dependencies.md
    - SDK Reference:
      - Shared Module: allsky_shared.md
      - Base Class: allsky_base.md
      - Allsky Server API: allsky_api.md
    - Contributing: developer_guide/contributing.md

